In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [4]:
%matplotlib inline

In [5]:
df = pd.read_csv("energydata_complete.csv")

In [7]:
df.sample(20)

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
9518,2016-03-17 19:20:00,110,10,22.823333,38.423333,20.390000,38.090000,21.790000,34.860000,22.200000,...,20.000000,35.260000,6.366667,764.233333,68.333333,2.000000,35.666667,0.866667,6.002439,6.002439
7034,2016-02-29 13:20:00,220,0,20.356667,33.156667,19.290000,32.700000,21.856667,38.223333,19.500000,...,18.200000,39.497500,5.333333,762.500000,52.000000,6.666667,32.000000,-3.833333,2.957497,2.957497
9324,2016-03-16 11:00:00,230,0,20.890000,39.900000,21.500000,38.133333,22.260000,38.526667,21.500000,...,19.700000,38.656667,6.500000,764.800000,56.000000,10.000000,40.000000,-1.700000,26.152242,26.152242
14189,2016-04-19 05:50:00,70,0,20.890000,38.590000,18.100000,42.400000,22.200000,36.400000,21.500000,...,20.290000,40.560000,5.216667,764.283333,94.000000,2.000000,24.000000,4.316667,48.977460,48.977460
2605,2016-01-29 19:10:00,70,10,19.633333,45.000000,19.290000,44.126667,19.500000,43.933333,16.700000,...,16.200000,45.933333,9.000000,762.283333,82.000000,10.000000,40.000000,6.100000,34.159885,34.159885
17639,2016-05-13 04:50:00,50,0,24.890000,47.590000,22.790000,49.400000,26.600000,43.826667,25.000000,...,24.290000,48.900000,12.300000,745.866667,96.166667,1.000000,36.666667,11.716667,22.465785,22.465785
10731,2016-03-26 05:30:00,50,0,21.790000,37.290000,18.100000,42.790000,23.290000,37.700000,20.166667,...,19.790000,42.290000,3.350000,757.400000,87.000000,3.500000,23.000000,1.400000,2.281636,2.281636
15564,2016-04-28 19:00:00,200,0,21.200000,33.500000,19.790000,31.926667,23.700000,38.060000,20.500000,...,18.790000,29.166667,9.800000,756.200000,41.000000,5.000000,40.000000,-3.000000,48.469124,48.469124
11455,2016-03-31 06:10:00,50,0,21.700000,40.200000,18.823333,44.326667,22.600000,38.290000,20.600000,...,20.390000,43.090000,5.983333,753.750000,97.500000,1.833333,63.333333,5.616667,20.330638,20.330638
4256,2016-02-10 06:20:00,70,0,21.100000,41.700000,20.500000,40.000000,22.390000,43.090000,18.700000,...,19.100000,46.290000,2.500000,739.433333,94.000000,7.000000,40.000000,1.600000,3.435501,3.435501
12815,2016-04-09 16:50:00,170,0,22.566667,44.900000,21.890000,41.160000,22.600000,39.300000,21.000000,...,20.500000,35.845000,13.883333,748.550000,50.666667,7.000000,40.000000,3.683333,28.332656,28.332656
19566,2016-05-26 14:00:00,80,0,24.200000,41.900000,25.968571,35.354286,26.650000,37.745000,24.426667,...,22.600000,43.700000,19.800000,756.800000,48.000000,2.000000,29.000000,8.500000,45.980144,45.980144
1509,2016-01-22 04:30:00,50,0,19.125000,37.475000,18.133333,37.363333,19.166667,40.060000,16.600000,...,15.963333,42.500000,-1.000000,764.100000,87.000000,3.000000,62.000000,-2.900000,30.576590,30.576590
15000,2016-04-24 21:00:00,90,0,21.926667,35.500000,19.290000,37.500000,22.390000,34.000000,21.390000,...,20.200000,32.400000,4.100000,758.000000,82.000000,3.000000,40.000000,1.200000,10.668196,10.668196
217,2016-01-13 05:10:00,50,0,18.890000,44.200000,18.290000,44.000000,19.890000,45.090000,18.500000,...,17.200000,50.060000,5.166667,752.050000,90.000000,7.833333,22.166667,3.566667,47.667773,47.667773
15362,2016-04-27 09:20:00,80,10,20.500000,36.463333,18.193333,39.266667,21.390000,34.700000,20.500000,...,19.166667,38.933333,3.633333,751.133333,92.333333,4.000000,34.666667,2.533333,26.227767,26.227767
1116,2016-01-19 11:00:00,40,0,18.600000,40.500000,17.356667,40.900000,19.000000,39.790000,18.133333,...,16.600000,38.590000,-2.400000,757.400000,81.000000,1.000000,64.000000,-5.300000,15.403812,15.403812
8990,2016-03-14 03:20:00,40,0,20.600000,35.200000,17.290000,39.590000,20.390000,36.966667,19.600000,...,19.290000,39.290000,0.766667,768.600000,89.000000,3.000000,63.000000,-0.900000,45.910144,45.910144
7621,2016-03-04 15:10:00,350,0,20.921429,36.161429,19.268571,35.867143,21.478333,40.500000,19.114286,...,18.500000,38.880000,5.400000,738.850000,83.500000,2.666667,30.000000,2.733333,22.318148,22.318148
10174,2016-03-22 08:40:00,50,0,21.100000,38.090000,18.100000,42.363333,21.790000,36.530000,20.323333,...,19.600000,39.200000,4.466667,758.133333,90.333333,1.000000,53.000000,2.966667,5.535764,5.535764

In [9]:
df.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [10]:
df.describe(include="all").transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
date,19735,19735,2016-04-23 07:40:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Appliances,19735,NaN,NaN,NaN,97.695,102.525,10,50,60,100,1080
lights,19735,NaN,NaN,NaN,3.80187,7.93599,0,0,0,0,70
T1,19735,NaN,NaN,NaN,21.6866,1.60607,16.79,20.76,21.6,22.6,26.26
RH_1,19735,NaN,NaN,NaN,40.2597,3.9793,27.0233,37.3333,39.6567,43.0667,63.36
T2,19735,NaN,NaN,NaN,20.3412,2.19297,16.1,18.79,20,21.5,29.8567
RH_2,19735,NaN,NaN,NaN,40.4204,4.06981,20.4633,37.9,40.5,43.26,56.0267
T3,19735,NaN,NaN,NaN,22.2676,2.00611,17.2,20.79,22.1,23.29,29.236
RH_3,19735,NaN,NaN,NaN,39.2425,3.25458,28.7667,36.9,38.53,41.76,50.1633
T4,19735,NaN,NaN,NaN,20.8553,2.04288,15.1,19.53,20.6667,22.1,26.2
RH_4,19735,NaN,NaN,NaN,39.0269,4.34132,27.66,35.53,38.4,42.1567,51.09
T5,19735,NaN,NaN,NaN,19.5921,1.84462,15.33,18.2775,19.39,20.6196,25.795
RH_5,19735,NaN,NaN,NaN,50.9493,9.02203,29.815,45.4,49.09,53.6633,96.3217
T6,19735,NaN,NaN,NaN,7.91094,6.09035,-6.065,3.62667,7.3,11.256,28.29
RH_6,19735,NaN,NaN,NaN,54.6091,31.1498,1,30.025,55.29,83.2267,99.9
T7,19735,NaN,NaN,NaN,20.2671,2.10999,15.39,18.7,20.0333,21.6,26
RH_7,19735,NaN,NaN,NaN,35.3882,5.11421,23.2,31.5,34.8633,39,51.4
T8,19735,NaN,NaN,NaN,22.0291,1.95616,16.3067,20.79,22.1,23.39,27.23
RH_8,19735,NaN,NaN,NaN,42.9362,5.22436,29.6,39.0667,42.375,46.536,58.78
T9,19735,NaN,NaN,NaN,19.4858,2.01471,14.89,18,19.39,20.6,24.5
RH_9,19735,NaN,NaN,NaN,41.5524,4.1515,29.1667,38.5,40.9,44.3381,53.3267
T_out,19735,NaN,NaN,NaN,7.41166,5.31741,-5,3.66667,6.91667,10.4083,26.1
Press_mm_hg,19735,NaN,NaN,NaN,755.523,7.39944,729.3,750.933,756.1,760.933,772.3
RH_out,19735,NaN,NaN,NaN,79.7504,14.9011,24,70.3333,83.6667,91.6667,100
Windspeed,19735,NaN,NaN,NaN,4.03975,2.45122,0,2,3.66667,5.5,14
Visibility,19735,NaN,NaN,NaN,38.3308,11.7947,1,29,40,40,66
Tdewpoint,19735,NaN,NaN,NaN,3.76071,4.19465,-6.6,0.9,3.43333,6.56667,15.5
rv1,19735,NaN,NaN,NaN,24.988,14.4966,0.00532168,12.4979,24.8977,37.5838,49.9965
rv2,19735,NaN,NaN,NaN,24.988,14.4966,0.00532168,12.4979,24.8977,37.5838,49.9965

##### To drop data and lights features as contained in the instruction

In [13]:
df.drop(["date", "lights"], axis=1, inplace=True) ## Drop the date column

##### Normalizing using MinMaxScaler

In [14]:
normalized_df = pd.DataFrame(MinMaxScaler().fit_transform(df), columns = df.columns)

In [70]:
normalized_df.corr()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
Appliances,1.000000,0.055447,0.086031,0.120073,-0.060465,0.085060,0.036292,0.040281,0.016965,0.019760,...,0.010010,-0.051462,0.099155,-0.034885,-0.152282,0.087122,0.000230,0.015353,-0.011145,-0.011145
T1,0.055447,1.000000,0.164006,0.836834,-0.002509,0.892402,-0.028550,0.877001,0.097861,0.885247,...,0.844777,0.071756,0.682846,-0.150574,-0.345481,-0.087654,-0.076210,0.571309,-0.006203,-0.006203
RH_1,0.086031,0.164006,1.000000,0.269839,0.797535,0.253230,0.844677,0.106180,0.880359,0.205797,...,0.115263,0.764001,0.340767,-0.293957,0.274126,0.204932,-0.021057,0.639106,-0.000699,-0.000699
T2,0.120073,0.836834,0.269839,1.000000,-0.165610,0.735245,0.121497,0.762066,0.231563,0.720550,...,0.675535,0.157346,0.792255,-0.133028,-0.505291,0.052495,-0.069721,0.582602,-0.011087,-0.011087
RH_2,-0.060465,-0.002509,0.797535,-0.165610,1.000000,0.137319,0.678326,-0.047304,0.721435,0.110409,...,0.054544,0.676467,0.033674,-0.255646,0.584911,0.069190,-0.005368,0.499152,0.006275,0.006275
T3,0.085060,0.892402,0.253230,0.735245,0.137319,1.000000,-0.011234,0.852778,0.122737,0.888169,...,0.901324,0.134602,0.699417,-0.189974,-0.281718,-0.100776,-0.102310,0.645886,-0.005194,-0.005194
RH_3,0.036292,-0.028550,0.844677,0.121497,0.678326,-0.011234,1.000000,-0.140457,0.898978,-0.050062,...,-0.195270,0.833538,0.118207,-0.233274,0.356192,0.263188,0.017041,0.414387,-0.000477,-0.000477
T4,0.040281,0.877001,0.106180,0.762066,-0.047304,0.852778,-0.140457,1.000000,-0.048650,0.871813,...,0.889439,-0.025549,0.663478,-0.075292,-0.388602,-0.185747,-0.104768,0.519471,-0.001815,-0.001815
RH_4,0.016965,0.097861,0.880359,0.231563,0.721435,0.122737,0.898978,-0.048650,1.000000,0.091812,...,-0.044518,0.856591,0.293289,-0.250748,0.336813,0.300192,0.002636,0.616509,-0.001787,-0.001787
T5,0.019760,0.885247,0.205797,0.720550,0.110409,0.888169,-0.050062,0.871813,0.091812,1.000000,...,0.911055,0.072308,0.651321,-0.170999,-0.273953,-0.145011,-0.084164,0.588362,-0.005490,-0.005490
RH_5,0.006955,-0.014782,0.303258,0.029595,0.250271,-0.066355,0.375422,-0.076489,0.352591,0.032786,...,-0.138509,0.272197,-0.053126,-0.119327,0.185941,0.082044,-0.013133,0.078175,-0.011056,-0.011056
T6,0.117638,0.654769,0.316141,0.801186,-0.009670,0.686882,0.076833,0.652350,0.259047,0.629161,...,0.667177,0.184424,0.974787,-0.141643,-0.569119,0.169185,-0.081313,0.764242,-0.015086,-0.015086
RH_6,-0.083178,-0.615045,0.245126,-0.580372,0.389933,-0.647672,0.514912,-0.703149,0.392178,-0.632384,...,-0.738940,0.391943,-0.641572,-0.065814,0.718587,0.098317,0.108705,-0.260417,0.011671,0.011671
T7,0.025801,0.838705,0.021397,0.663660,-0.051422,0.847374,-0.250090,0.877763,-0.131204,0.870624,...,0.944776,-0.077690,0.631293,-0.097724,-0.411213,-0.185892,-0.110089,0.466625,-0.003900,-0.003900
RH_7,-0.055642,0.135182,0.801122,0.229212,0.690584,0.172624,0.832685,0.043527,0.894301,0.148905,...,0.028055,0.858686,0.294199,-0.265850,0.378519,0.212979,-0.007184,0.641857,0.001820,0.001820
T8,0.039572,0.825413,-0.030053,0.578191,-0.041023,0.795283,-0.283228,0.796256,-0.167066,0.824981,...,0.869338,-0.156820,0.502842,-0.162855,-0.300438,-0.218876,-0.060098,0.391810,-0.003210,-0.003210
RH_8,-0.094039,-0.006441,0.736196,0.068534,0.679777,0.044427,0.828822,-0.095192,0.847259,0.016388,...,-0.113014,0.855812,0.117141,-0.225591,0.487355,0.202380,0.046178,0.501775,0.004480,0.004480
T9,0.010010,0.844777,0.115263,0.675535,0.054544,0.901324,-0.195270,0.889439,-0.044518,0.911055,...,1.000000,-0.008683,0.668220,-0.156828,-0.318848,-0.177756,-0.103915,0.581483,-0.001227,-0.001227
RH_9,-0.051462,0.071756,0.764001,0.157346,0.676467,0.134602,0.833538,-0.025549,0.856591,0.072308,...,-0.008683,1.000000,0.223270,-0.183739,0.359377,0.238655,0.008667,0.540328,-0.002955,-0.002955
T_out,0.099155,0.682846,0.340767,0.792255,0.033674,0.699417,0.118207,0.663478,0.293289,0.651321,...,0.668220,0.223270,1.000000,-0.143249,-0.574197,0.192936,-0.077367,0.790661,-0.015216,-0.015216
Press_mm_hg,-0.034885,-0.150574,-0.293957,-0.133028,-0.255646,-0.189974,-0.233274,-0.075292,-0.250748,-0.170999,...,-0.156828,-0.183739,-0.143249,1.000000,-0.092017,-0.235032,0.040315,-0.244098,0.000699,0.000699
RH_out,-0.152282,-0.345481,0.274126,-0.505291,0.584911,-0.281718,0.356192,-0.388602,0.336813,-0.273953,...,-0.318848,0.359377,-0.574197,-0.092017,1.000000,-0.176458,0.083125,0.036506,0.020441,0.020441
Windspeed,0.087122,-0.087654,0.204932,0.052495,0.069190,-0.100776,0.263188,-0.185747,0.300192,-0.145011,...,-0.177756,0.238655,0.192936,-0.235032,-0.176458,1.000000,-0.007516,0.125972,-0.011342,-0.011342
Visibility,0.000230,-0.076210,-0.021057,-0.069721,-0.005368,-0.102310,0.017041,-0.104768,0.002636,-0.084164,...,-0.103915,0.008667,-0.077367,0.040315,0.083125,-0.007516,1.000000,-0.042190,-0.005889,-0.005889
Tdewpoint,0.015353,0.571309,0.639106,0.582602,0.499152,0.645886,0.414387,0.519471,0.616509,0.588362,...,0.581483,0.540328,0.790661,-0.244098,0.036506,0.125972,-0.042190,1.000000,-0.003943,-0.003943
rv1,-0.011145,-0.006203,-0.000699,-0.011087,0.006275,-0.005194,-0.000477,-0.001815,-0.001787,-0.005490,...,-0.001227,-0.002955,-0.015216,0.000699,0.020441,-0.011342,-0.005889,-0.003943,1.000000,1.000000
rv2,-0.011145,-0.006203,-0.000699,-0.011087,0.006275,-0.005194,-0.000477,-0.001815,-0.001787,-0.005490,...,-0.001227,-0.002955,-0.015216,0.000699,0.020441,-0.011342,-0.005889,-0.003943,1.000000,1.000000

## To Answer the Quiz Questions

#### From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the R^2 value in two D.P?

In [25]:
Xi = np.array([normalized_df["T2"]]).reshape(-1, 1)
yi = np.array([normalized_df["T6"]]).reshape(-1, 1)


Xi_train, Xi_test, yi_train, yi_test = train_test_split(Xi, yi, test_size=0.3, random_state=42)

In [28]:
lmm = LinearRegression()
lmm.fit(Xi_train, yi_train)


round(metrics.r2_score(yi_test, lmm.predict(Xi_test)), 2)

0.64

#### What is the Mean Absolute Error (in two decimal places)?

In [ ]:
y = normalized_df["Appliances"]
X = normalized_df.drop("Appliances", axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [69]:
## LinearRigression Model

reg = LinearRegression()
reg.fit(X_train, y_train)

print("MAE", metrics.mean_absolute_error(y_test, reg.predict(X_test)))

MAE 0.05013362397742954

#### What is the Residual Sum of Squares (in two decimal places)?

In [34]:
print("RSS", round(np.sum(np.square(y_test, predict))), 2)

RSS 93.0 2

##### What is the Root Mean Squared Error (in three decimal places)?

In [35]:
print("RMSE", round(np.sqrt(metrics.mean_squared_error(y_test, predict))), 3)

RMSE 0.0 3

##### What is the Coefficient of Determination (in two decimal places)?

In [36]:
print("R_2", metrics.r2_score(y_test, predict))

R_2 0.20545493424595573

##### Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

In [57]:
linearReg_coef = pd.DataFrame(reg.coef_, X_train.columns, columns =["Coef"] ).reset_index()
linearReg_coef.columns = ["features","coef"]

print(linearReg_coef.min())
print(linearReg_coef.max())

features    Press_mm_hg
coef          -0.456698
dtype: object
features         rv2
coef        0.553547
dtype: object

##### Train a ridge regression model with an alpha value of 0.4. Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

In [66]:
def RMSE_ridge_calculate(alpha):
    ### A finction to check if the RMSE with alpha change is the same
    
    RMSE1 = list()
    for alpha in alpha:
        ridge = Ridge(alpha)
        ridge.fit(X_train, y_train)
       
        prediction = ridge.predict(X_test)
        
        RMSE = round(np.sqrt(metrics.mean_squared_error(y_test, prediction)))
        if RMSE not in RMSE1:
            RMSE1.append(RMSE)
            if len(RMSE1)!=1:
                print("YES: Thers's changes")
        else:
            print("NO: No change")
RMSE_ridge_calculate([0, 0.4])

NO: No change

##### Train a lasso regression model with an alpha value of 0.001 and obtain the new feature weights with it. How many of the features have non-zero feature weights?

In [108]:
lasso = Lasso(alpha=0.001)
lasso.fit(X_train, y_train)


lasso_coef = pd.DataFrame(lasso.coef_, X_train.columns, columns =["coef"] ).reset_index()
lasso_coef.columns = ["features","coef"]
lasso_coef

#lasso_coef.query('coef=="0"').count()

       features      coef
0            T1  0.000000
1          RH_1  0.017880
2            T2  0.000000
3          RH_2 -0.000000
4            T3  0.000000
5          RH_3  0.000000
6            T4 -0.000000
7          RH_4  0.000000
8            T5 -0.000000
9          RH_5  0.000000
10           T6  0.000000
11         RH_6 -0.000000
12           T7 -0.000000
13         RH_7 -0.000000
14           T8  0.000000
15         RH_8 -0.000110
16           T9 -0.000000
17         RH_9 -0.000000
18        T_out  0.000000
19  Press_mm_hg -0.000000
20       RH_out -0.049557
21    Windspeed  0.002912
22   Visibility  0.000000
23    Tdewpoint  0.000000
24          rv1 -0.000000
25          rv2 -0.000000

#### What is the new RMSE with the Lasso Regression (in 3 decimal places)?

In [82]:
print("Lasso RMSE", round(np.sqrt(metrics.mean_squared_error(y_test, lasso.predict(X_test)))))

Lasso RMSE 0.0